@file:Repository("https://maven.pkg.jetbrains.space/public/p/kotlinx-html/maven")
@file:DependsOn("org.jetbrains.kotlinx:kotlinx-html-jvm:0.7.3")

import kotlinx.html.*
import kotlinx.html.stream.createHTML
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardOpenOption

fun writePage(fileName: String, block: HTML.() -> Unit) {
	val html = createHTML().html(block = block)
	Files.writeString(
		Path.of(fileName),
		"<!DOCTYPE html>\n$html",
		StandardOpenOption.CREATE,
		StandardOpenOption.TRUNCATE_EXISTING
	)
}

writePage("test.html") {
	head {
		title("My Kotlin Site")
	}
	body {
		h1 { +"Hello from Kotlin Script" }
		p { +"This page was generated by Kotlin." }
	}
}